package com.example.paymentecho.mapper

import com.example.paymentecho.dto.PaymentRequest
import com.example.paymentecho.dto.PaymentResponse
import com.example.paymentecho.dto.request.PaymentCreateRequest
import com.example.paymentecho.dto.request.PaymentEchoRequest
import com.example.paymentecho.dto.response.PaymentResponse as ResponsePaymentResponse
import com.example.paymentecho.entity.Payment
import com.example.paymentecho.repository.CreditorRepository
import com.example.paymentecho.repository.DebtorRepository
import org.springframework.stereotype.Component
import java.util.*

/**
 * Simple stateless mapper. For larger projects consider using MapStruct or Kotlin reflection-based mappers.
 * Keep mapping in a single place for easier audits and future field renames.
 */

@Component
class PaymentMapper(
    private val creditorRepository: CreditorRepository,
    private val debtorRepository: DebtorRepository
) {

    fun toEntity(req: PaymentRequest): Payment {
        // Note: ID is generated by DB; createdAt is set by entity default
        return Payment(
            id = null,
            amount = req.amount ?: 0.0,
            currency = req.currency,
            status = req.status ?: "RECEIVED"
            // externalReference intentionally not stored in this simplified entity;
            // extend entity and DB schema if needed.
        )
    }

    fun toEntity(req: PaymentCreateRequest): Payment {
        val creditor = req.creditorId?.let { creditorRepository.findById(it).orElse(null) }
        val debtor = req.debtorId?.let { debtorRepository.findById(it).orElse(null) }
        return Payment(
            id = null,
            amount = req.amount,
            currency = req.currency,
            status = req.status,
            creditor = creditor,
            debtor = debtor
        )
    }

    fun toEntity(req: PaymentEchoRequest): Payment {
        val creditor = req.creditorId?.let { creditorRepository.findById(it).orElse(null) }
        val debtor = req.debtorId?.let { debtorRepository.findById(it).orElse(null) }
        return Payment(
            id = null,
            amount = req.amount,
            currency = req.currency,
            status = req.status,
            creditor = creditor,
            debtor = debtor
        )
    }

    fun toResponse(entity: Payment): PaymentResponse =
        PaymentResponse(
            id = entity.id!!,
            amount = entity.amount,
            currency = entity.currency,
            status = entity.status,
            createdAt = entity.createdAt,
            externalReference = null // if you add this to entity, map it here
        )

    fun toResponseResponse(entity: Payment): ResponsePaymentResponse =
        ResponsePaymentResponse(
            id = entity.id!!,
            amount = entity.amount,
            currency = entity.currency,
            status = entity.status,
            createdAt = entity.createdAt,
            creditorId = entity.creditor?.id,
            debtorId = entity.debtor?.id
        )
}
