package com.example.paymentecho.mapper

import com.example.paymentecho.dto.PaymentRequest
import com.example.paymentecho.dto.PaymentResponse
import com.example.paymentecho.entity.Payment
import java.util.*

/**
 * Simple stateless mapper. For larger projects consider using MapStruct or Kotlin reflection-based mappers.
 * Keep mapping in a single place for easier audits and future field renames.
 */

object PaymentMapper {

    fun toEntity(req: PaymentRequest): Payment {
        // Note: ID is generated by DB; createdAt is set by entity default
        return Payment(
            id = null,
            amount = req.amount ?: 0.0,
            currency = req.currency,
            status = req.status ?: "RECEIVED"
            // externalReference intentionally not stored in this simplified entity;
            // extend entity and DB schema if needed.
        )
    }

    fun toResponse(entity: Payment): PaymentResponse =
        PaymentResponse(
            id = entity.id!!,
            amount = entity.amount,
            currency = entity.currency,
            status = entity.status,
            createdAt = entity.createdAt,
            externalReference = null // if you add this to entity, map it here
        )
}
